### ISSUE TITLE
A 101 example for keyboard flying is needed, 

### ISSUE THREAD

**Issue by benmoshe** [AlonBarak-dev/Tello-Semi-Autonomous#1]
preferably without the need to use ROS2

**Comment by AlonBarak-dev** [comment]
כן, אפתח אופציה להשתמש ללא רוס2

בתאריך יום ו׳, 2 בספט׳ 2022 ב-9:46 מאת Boaz Benmoshe <
***@***.***>:

**Comment by AlonBarak-dev** [comment]
Keyboard Interface has been added to the Repository!
